services:
  postgres:
    image: postgres:15-alpine
    container_name: arcanus-vpn-postgres
    environment:
      POSTGRES_DB: arcanus_vpn_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d arcanus_vpn_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arcanus-vpn-bot
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DATABASE_URL: postgres://testuser:testpass@postgres:5432/arcanus_vpn_test?sslmode=disable
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    # volumes:
    #   - .:/app
    command: ./main

volumes:
  postgres_data:
